Add support for serde_qs
rambler-digital-solutions/actix-web-validator pull request #23
Opened 2021-05-06 10:19 UTC by rlebran

Hello,

In one of our projects we use serde_qs and we would like to have the ability to validate the request using validator.
Please see if this is a functionality you like to have in this crate.

If you want me to add the functionality though a feature flag instead don't hesitate to tell me.

2021-05-16 22:14 UTC, singulared requested changes

2021-05-16 22:14 UTC, singulared commented on Cargo.toml
> +serde_qs = { version = "0", features = ["actix"] }
Non-stable 0.x.x crates can change public API in minor release and I think should be locked in minor version

2021-05-16 22:15 UTC, singulared commented
Thanks a lot for your PR and sorry for my delay. :)

2021-05-17 05:28 UTC, rlebran commented
I fixed serde_qs to version 0.8. Hope it's good for you.
No problem for the delay :)

2021-05-18 20:51 UTC, merged