upgrade validator version
rambler-digital-solutions/actix-web-validator pull request #54
Opened 2024-04-08 09:21 UTC by chunhui2001

2024-04-28 18:51 UTC, DenuxPlays commented
Tested it.
Works great!

2024-05-08 11:25 UTC, DasKoebi requested changes
I dont think this PR will be merged with the following changes.

2024-05-08 11:25 UTC, DasKoebi commented on Cargo.toml
> +authors = ["keesh.zhang<chunhui2001@gmail.com>"]
Was this change intended?

2024-05-08 11:25 UTC, DasKoebi commented on Cargo.toml
> +documentation = "https://docs.rs/actix-web-validator5"
Was this change intended?

2024-07-11 08:50 UTC, singulared commented
Thanks a lot for your work but i close this PR in prefer to #55

2024-07-11 08:50 UTC, closed without merging